version: '3.5'

services:
  web:
    container_name: ${COMPOSE_PROJECT_NAME}_web
    image: nginx:latest
    environment:
      VIRTUAL_HOST: ${SITE_DOMAIN}
      LETSENCRYPT_HOST: ${LE_HOST}
      LETSENCRYPT_EMAIL: ${MAIN_USER_EMAIL}
      VIRTUAL_PORT: 443
      VIRTUAL_PROTO: https
      HSTS: 'max-age=3600; includeSubDomains; preload'
    volumes:
      - ./app:/app:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/fastcgi_conf:/etc/nginx/fastcgi_conf:ro
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./conf/certs:/certs:ro
      - ./logs/nginx:/var/log/nginx
    expose:
      - 80
      - 443
    restart: ${RESTART_MODE}
    depends_on:
      - fpm
  fpm:
    container_name: ${COMPOSE_PROJECT_NAME}_fpm
    build:
      context: .
      dockerfile: Dockerfile
    image: php7.2:yii
    volumes:
      - ./app:/app
      - ./.env:/app/.env
      - ./conf/php/fpm.conf:/etc/php/7.2/fpm/php-fpm.d/zz-fpm.conf:ro
      - ./conf/php/php-${APP_MODE}.ini:/etc/php/7.2/cli/conf.d/zz-php.ini:ro
      - ./conf/php/php-${APP_MODE}.ini:/etc/php/7.2/fpm/conf.d/zz-php.ini:ro
      - ./conf/composer/auth.json:/root/.composer/auth.json:ro
      - ./conf/composer/auth.json:/root/.config/composer/auth.json:ro
      - ./logs/php:/var/log/php
      - ./logs/fpm:/var/log/fpm
    restart: ${RESTART_MODE}
    depends_on:
      - db
  db:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./conf/postgresql:/etc/postgresql/10/main/conf.d
      - db-data:/var/lib/postgresql/data
      - ./logs/postgresql:/var/log/postgresql
    restart: ${RESTART_MODE}

networks:
    default:
       external:
         name: webproxy

volumes:
  db-data:
    name: ${COMPOSE_PROJECT_NAME}_db-data
